[workspace]
resolver = "2"
members = ["imessage-database", "imessage-undeleter"]

[profile.release]
# Perform Link Time Optimization
lto = true
# Use a single codegen unit for the entire crate
codegen-units = 1
# Do not unwind stack on crash
panic = "abort"
